# Generated by Django 3.0.5 on 2020-05-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutedTask',
            fields=[
                ('owner_id', models.IntegerField()),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('parent_planned_task_id', models.IntegerField()),
                ('runStart', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('taskName', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('offersType', models.CharField(max_length=100)),
                ('regions', models.CharField(blank=True, max_length=1000)),
                ('localizations', models.CharField(blank=True, max_length=1000)),
                ('firstRun', models.DateTimeField()),
                ('recurring', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('nextRun', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrappedOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('task_run_id', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('level', models.IntegerField(null=True)),
                ('size', models.CharField(max_length=100)),
                ('rooms', models.IntegerField()),
                ('market', models.CharField(max_length=100)),
                ('building_type', models.CharField(max_length=100, null=True)),
                ('price_per_msq', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('verified', models.BooleanField()),
                ('verificationCode', models.CharField(max_length=100)),
            ],
        ),
    ]
